SET SCHEMA TUKGRP2 ;

DROP TYPE PAL_KMEANS_DATA_T;
CREATE TYPE PAL_KMEANS_DATA_T AS TABLE(
	"ID" INTEGER,
	"DROPOFF_LONG" DOUBLE,
	"DROPOFF_LAT" DOUBLE
);

DROP TYPE PAL_CONTROL_T;
CREATE TYPE PAL_CONTROL_T AS TABLE(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);

DROP TYPE PAL_KMEANS_ASSIGNED_T;
CREATE TYPE PAL_KMEANS_ASSIGNED_T AS TABLE(
	"ID" INTEGER,
	"CLUSTER" INTEGER,
	"DISTANCE" DOUBLE,
	"SLIGHT_SILHOUETTE" DOUBLE
);

DROP TYPE PAL_KMEANS_CENTERS_T;
CREATE TYPE PAL_KMEANS_CENTERS_T AS TABLE(
	"CLUSTER_ID" INTEGER,
	"DROPOFF_LONG" DOUBLE,
	"DROPOFF_LAT" DOUBLE
);


DROP TYPE PAL_KMEANS_SIL_CENTERS_T;
CREATE TYPE PAL_KMEANS_SIL_CENTERS_T AS TABLE(
	"CLUSTER_ID" INTEGER,
	"SLIGHT_SILHOUETTE" DOUBLE
);

DROP TYPE PAL_KMEANS_STATISTIC_T;
CREATE TYPE PAL_KMEANS_STATISTIC_T AS TABLE(
	"NAME" VARCHAR(50),
	"VALUE" DOUBLE
);

DROP TABLE PAL_KMEANS_PDATA_TBL;
CREATE COLUMN TABLE PAL_KMEANS_PDATA_TBL("POSITION" INT, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (1, 'TUKGRP2', 'PAL_KMEANS_DATA_T', 'IN');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (2, 'TUKGRP2', 'PAL_CONTROL_T', 'IN');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (3, 'TUKGRP2', 'PAL_KMEANS_ASSIGNED_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (4, 'TUKGRP2', 'PAL_KMEANS_CENTERS_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (5, 'TUKGRP2', 'PAL_KMEANS_SIL_CENTERS_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (6, 'TUKGRP2', 'PAL_KMEANS_STATISTIC_T', 'OUT');


CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_DROP('TUKGRP2', 'PAL_KMEANS_PROC');

CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'KMEANS', 'TUKGRP2', 'PAL_KMEANS_PROC', PAL_KMEANS_PDATA_TBL);


DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_1_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_1_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_1_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_1_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_1_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_1_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_1_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_1_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_1_ITERATION, PAL_KMEANS_CENTERS_TBL_1_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_1_ITERATION, PAL_KMEANS_STATISTIC_TBL_1_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_2_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_2_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_2_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_2_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_2_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_2_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_2_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_2_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_2_ITERATION, PAL_KMEANS_CENTERS_TBL_2_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_2_ITERATION, PAL_KMEANS_STATISTIC_TBL_2_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 3, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_3_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_3_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_3_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_3_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_3_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_3_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_3_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_3_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_3_ITERATION, PAL_KMEANS_CENTERS_TBL_3_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_3_ITERATION, PAL_KMEANS_STATISTIC_TBL_3_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 4, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_4_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_4_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_4_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_4_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_4_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_4_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_4_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_4_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_4_ITERATION, PAL_KMEANS_CENTERS_TBL_4_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_4_ITERATION, PAL_KMEANS_STATISTIC_TBL_4_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 5, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_5_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_5_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_5_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_5_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_5_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_5_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_5_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_5_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_5_ITERATION, PAL_KMEANS_CENTERS_TBL_5_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_5_ITERATION, PAL_KMEANS_STATISTIC_TBL_5_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 6, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_6_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_6_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_6_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_6_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_6_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_6_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_6_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_6_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_6_ITERATION, PAL_KMEANS_CENTERS_TBL_6_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_6_ITERATION, PAL_KMEANS_STATISTIC_TBL_6_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 7, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_7_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_7_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_7_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_7_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_7_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_7_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_7_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_7_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_7_ITERATION, PAL_KMEANS_CENTERS_TBL_7_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_7_ITERATION, PAL_KMEANS_STATISTIC_TBL_7_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 8, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_8_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_8_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_8_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_8_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_8_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_8_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_8_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_8_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_8_ITERATION, PAL_KMEANS_CENTERS_TBL_8_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_8_ITERATION, PAL_KMEANS_STATISTIC_TBL_8_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 9, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_9_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_9_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_9_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_9_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_9_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_9_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_9_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_9_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_9_ITERATION, PAL_KMEANS_CENTERS_TBL_9_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_9_ITERATION, PAL_KMEANS_STATISTIC_TBL_9_ITERATION) with OVERVIEW;

-------

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 80, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 20, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 10, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);


DROP TABLE PAL_KMEANS_ASSIGNED_TBL_10_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL_10_ITERATION LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL_10_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL_10_ITERATION LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL_10_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL_10_ITERATION LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL_10_ITERATION;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL_10_ITERATION LIKE PAL_KMEANS_STATISTIC_T;


CALL "TUKGRP2".PAL_KMEANS_PROC("TUKGRP2"."TRIP_DROPOFF_2013_CLEAN", #PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL_10_ITERATION, PAL_KMEANS_CENTERS_TBL_10_ITERATION, PAL_KMEANS_SIL_CENTERS_TBL_10_ITERATION, PAL_KMEANS_STATISTIC_TBL_10_ITERATION) with OVERVIEW;
